server:
  port: 9002

spring:
  application:
    name: AUCTION-SERVICE
  data-source:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  rabbitmq:
    addresses: localhost:5672
    queue: auction_mail_queue
    exchange: auction_mail_queue
  zipkin:
    base-url: http://localhost:9411/zipkin/